server:
    port: 8888

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/NonSpinning/DWB2023-2-config-data.git
                    search-paths: api
                    default-label: "main"

    security:
        user:
            name: root
            password: adminadmin
